"""
Extract concept-annotated rows from SEC R*.htm report files.

Each R*.htm file is a pre-rendered HTML table generated by the SEC for the
Interactive Data Viewer. Every row's label cell contains an onclick handler
with the XBRL concept ID:

    onclick="Show.showAR(this, 'defref_us-gaap_Assets', window)"

This module parses these files to produce ConceptRow objects that pair
labels and values with their authoritative XBRL concept identifiers.

Row CSS classes encode semantics:
    re/ro   — regular even/odd data rows
    reu/rou — underlined (subtotal/total) rows
    rh      — section header (dimensional member or axis label)

Value cell classes:
    nump — positive numeric
    num  — negative numeric (parenthetical)
    text — non-numeric (empty or label)
"""
import re
from dataclasses import dataclass
from typing import Dict, List, Optional

from bs4 import BeautifulSoup, Tag

__all__ = ['ConceptRow', 'ConceptReport', 'extract_concepts_from_report', 'parse_numeric']

_DEFREF_RE = re.compile(r"defref_([^'\"]+)")
_TOTAL_CLASSES = frozenset({'reu', 'rou'})
_HEADER_CLASSES = frozenset({'rh'})
_DATA_CLASSES = frozenset({'re', 'ro', 'reu', 'rou', 'rh'})

_SCALING_MAP = {
    'millions': 1_000_000,
    'thousands': 1_000,
    'billions': 1_000_000_000,
    'hundreds': 100,
}


def parse_numeric(value_str: str) -> Optional[float]:
    """
    Parse a display value like '$ 95,359' or '(279)' into a float.

    Handles currency symbols, commas, parenthetical negatives, and unicode minus.
    Returns None for empty or non-numeric strings.
    """
    if not value_str:
        return None
    cleaned = value_str.replace('$', '').replace(',', '').replace(' ', '').strip()
    if cleaned.startswith('(') and cleaned.endswith(')'):
        cleaned = '-' + cleaned[1:-1]
    cleaned = cleaned.replace('−', '-')  # unicode minus
    try:
        return float(cleaned)
    except ValueError:
        return None


@dataclass
class ConceptRow:
    """A single row from an R*.htm report with concept annotation."""
    concept_id: str
    label: str
    values: Dict[str, str]
    is_abstract: bool
    is_total: bool
    is_header: bool
    level: int
    css_class: str

    @property
    def namespace(self) -> str:
        """Extract namespace prefix (e.g., 'us-gaap' from 'us-gaap_Assets')."""
        parts = self.concept_id.split('_', 1)
        return parts[0] if len(parts) > 1 else ''

    @property
    def localname(self) -> str:
        """Extract local concept name (e.g., 'Assets' from 'us-gaap_Assets')."""
        parts = self.concept_id.split('_', 1)
        return parts[1] if len(parts) > 1 else self.concept_id

    @property
    def is_dimensional(self) -> bool:
        """True if this is a dimensional header (axis=member pattern)."""
        return '=' in self.concept_id

    @property
    def numeric_value(self) -> Optional[float]:
        """First period value as a float, or None."""
        if not self.values:
            return None
        return parse_numeric(next(iter(self.values.values())))

    @property
    def numeric_values(self) -> Dict[str, Optional[float]]:
        """All period values parsed as floats."""
        return {k: parse_numeric(v) for k, v in self.values.items()}

    def __repr__(self):
        val_str = f", values={len(self.values)}" if self.values else ""
        return f"ConceptRow({self.concept_id}, label={self.label!r}{val_str})"


@dataclass
class ConceptReport:
    """A parsed R*.htm report with concept annotations extracted."""
    title: str
    period_headers: List[str]
    rows: List[ConceptRow]
    currency: str = 'USD'
    currency_scaling: int = 1
    shares_scaling: int = 1

    @property
    def concepts(self) -> List[str]:
        """Unique concept IDs in presentation order."""
        seen = set()
        result = []
        for row in self.rows:
            if row.concept_id not in seen:
                seen.add(row.concept_id)
                result.append(row.concept_id)
        return result

    @property
    def data_rows(self) -> List[ConceptRow]:
        """Non-abstract, non-header rows only."""
        return [r for r in self.rows if not r.is_abstract and not r.is_header]

    def get_by_concept(self, concept_id: str) -> List[ConceptRow]:
        """Get all rows for a given concept ID (may appear multiple times in dimensional reports)."""
        return [r for r in self.rows if r.concept_id == concept_id]

    def __len__(self):
        return len(self.rows)

    def __repr__(self):
        return f"ConceptReport({self.title!r}, rows={len(self.rows)}, periods={len(self.period_headers)})"


def _extract_concept_id(td: Tag) -> Optional[str]:
    """Extract the concept ID from a label cell's onclick handler."""
    a_tag = td.find('a')
    if not a_tag:
        return None
    onclick = a_tag.get('onclick', '')
    match = _DEFREF_RE.search(onclick)
    if match:
        return match.group(1)
    return None


def _extract_label(td: Tag) -> str:
    """Extract the display label text from a label cell."""
    a_tag = td.find('a')
    if a_tag:
        return a_tag.get_text(strip=True)
    return td.get_text(strip=True)


def _is_abstract_row(td: Tag, value_cells: List[Tag]) -> bool:
    """Detect abstract rows: bold label and all value cells are empty/text."""
    strong = td.find('strong')
    if not strong:
        return False
    # Check that all value cells are empty (class="text" or contain only nbsp)
    for cell in value_cells:
        css = cell.get('class', [])
        if isinstance(css, list):
            css = ' '.join(css)
        if 'nump' in css or 'num' in css:
            return False
    return True


def _extract_value(td: Tag) -> str:
    """Extract the display value from a value cell, preserving sign indicators."""
    text = td.get_text(strip=True)
    # Clean up common HTML entities
    text = text.replace('\xa0', '').replace('\u200b', '')
    return text if text else ''


def _detect_level(td: Tag) -> int:
    """Detect indentation level from padding-left style or nesting."""
    style = td.get('style', '')
    # Some R*.htm files use padding-left for indentation
    match = re.search(r'padding-left:\s*(\d+)', style)
    if match:
        px = int(match.group(1))
        return max(0, px // 10)  # Rough estimate: 10px per level
    return 0


def extract_concepts_from_report(html_content: str) -> ConceptReport:
    """
    Parse an R*.htm file and extract concept-annotated rows.

    Args:
        html_content: Raw HTML content of an R*.htm file

    Returns:
        ConceptReport with title, period headers, and concept-annotated rows
    """
    soup = BeautifulSoup(html_content, 'html.parser')

    # Find the main report table
    report_table = soup.find('table', class_='report')
    if not report_table:
        return ConceptReport(title='', period_headers=[], rows=[])

    # Extract title and scaling from the header cell
    title = ''
    currency = 'USD'
    currency_scaling = 1
    shares_scaling = 1
    tl = report_table.find('th', class_='tl')
    if tl:
        strong = tl.find('strong')
        if strong:
            full_header = strong.get_text()
            # Title is the first line (before <br>)
            title_parts = []
            for child in strong.children:
                if isinstance(child, Tag) and child.name == 'br':
                    break
                text = child.string if isinstance(child, str) else child.get_text()
                if text:
                    title_parts.append(text.strip())
            title = ' '.join(title_parts).strip()
            if not title:
                title = full_header.strip()
            # Parse scaling from lines after <br>
            # e.g., "shares in Thousands, $ in Millions"
            header_lower = full_header.lower()
            for word, factor in _SCALING_MAP.items():
                if f'$ in {word}' in header_lower or f'$in {word}' in header_lower:
                    currency_scaling = factor
                if f'shares in {word}' in header_lower:
                    shares_scaling = factor

    # Extract period headers from <th class="th"> cells.
    # Group-spanning headers (colspan > 1) like "3 Months Ended" are captured
    # and prefixed to leaf headers for structured period identification.
    group_headers: List[tuple] = []  # (text, colspan)
    period_headers = []
    for th in report_table.find_all('th', class_='th'):
        div = th.find('div')
        text = div.get_text(strip=True) if div else th.get_text(strip=True)
        if not text:
            continue
        colspan = th.get('colspan')
        if colspan:
            try:
                cs = int(colspan)
            except ValueError:
                cs = 1
        else:
            cs = 1
        if cs > 1:
            group_headers.append((text, cs))
        else:
            # Find which group this leaf header belongs to
            prefix = ''
            col_pos = len(period_headers)
            offset = 0
            for grp_text, grp_span in group_headers:
                if offset <= col_pos < offset + grp_span:
                    prefix = grp_text
                    break
                offset += grp_span
            if prefix:
                period_headers.append(f"{prefix} {text}")
            else:
                period_headers.append(text)

    # Extract data rows
    rows = []
    for tr in report_table.find_all('tr', recursive=False):
        css_classes = tr.get('class', [])
        if isinstance(css_classes, list):
            row_class = css_classes[0] if css_classes else ''
        else:
            row_class = css_classes

        if row_class not in _DATA_CLASSES:
            continue

        # Find label cell (class="pl")
        label_cell = tr.find('td', class_='pl')
        if not label_cell:
            continue

        concept_id = _extract_concept_id(label_cell)
        if not concept_id:
            continue

        label = _extract_label(label_cell)
        level = _detect_level(label_cell)

        # Collect value cells (everything after the label cell)
        all_tds = tr.find_all('td', recursive=False)
        value_cells = [td for td in all_tds if td != label_cell]

        is_abstract = _is_abstract_row(label_cell, value_cells)
        is_total = row_class in _TOTAL_CLASSES
        is_header = row_class in _HEADER_CLASSES

        # Extract values keyed by period header
        values = {}
        for i, cell in enumerate(value_cells):
            val = _extract_value(cell)
            if val and i < len(period_headers):
                header = period_headers[i]
                # Handle duplicate period headers (e.g., "Mar. 29, 2025" appears twice)
                if header in values:
                    # Append index to disambiguate
                    header = f"{header} ({i})"
                values[header] = val

        rows.append(ConceptRow(
            concept_id=concept_id,
            label=label,
            values=values,
            is_abstract=is_abstract,
            is_total=is_total,
            is_header=is_header,
            level=level,
            css_class=row_class,
        ))

    return ConceptReport(
        title=title,
        period_headers=period_headers,
        rows=rows,
        currency=currency,
        currency_scaling=currency_scaling,
        shares_scaling=shares_scaling,
    )
