"""
Parser for MetaLinks.json — the SEC's rich XBRL metadata file.

MetaLinks.json is generated by the SEC for every XBRL filing and lives in the
SGML submission bundle alongside FilingSummary.xml and R*.htm files. It contains:

- Tag definitions with credit/debit indicator, xbrl type, labels, and FASB documentation
- Calculation relationships (parent-child trees per role)
- Presentation role assignments for every tag
- Authoritative references to FASB codification sections
- Report metadata matching FilingSummary.xml but with groupType/subGroupType

The data is structured as:
    {
      "version": "2.2",
      "instance": { "<filename>.htm": { "tag": {...}, "report": {...}, ... } },
      "std_ref": { "r0": {...}, "r1": {...}, ... }
    }
"""
import json
from dataclasses import dataclass
from typing import Dict, List, Optional

__all__ = ['MetaLinks', 'TagDefinition', 'CalculationEntry', 'MetaLinksReport', 'AuthRef']


@dataclass
class CalculationEntry:
    """Calculation relationship for a tag within a specific role."""
    role: str
    parent_tag: Optional[str]
    weight: Optional[float]
    order: Optional[float]
    root: bool


@dataclass
class TagDefinition:
    """A single XBRL concept/tag definition from MetaLinks.json."""
    tag_id: str
    xbrltype: str
    nsuri: str
    localname: str
    crdr: Optional[str]
    label: str
    terse_label: str
    total_label: Optional[str]
    documentation: str
    presentation: List[str]
    calculations: Dict[str, CalculationEntry]
    auth_ref_ids: List[str]

    @property
    def namespace(self) -> str:
        """Extract namespace prefix from tag_id (e.g., 'us-gaap' from 'us-gaap_Assets')."""
        parts = self.tag_id.split('_', 1)
        return parts[0] if len(parts) > 1 else ''

    @property
    def is_standard(self) -> bool:
        """True if this is a standard taxonomy tag (us-gaap, dei, srt, etc.)."""
        ns = self.namespace
        return ns in ('us-gaap', 'dei', 'srt', 'ecd', 'country', 'stpr', 'ifrs-full')

    @property
    def is_monetary(self) -> bool:
        return self.xbrltype == 'monetaryItemType'

    @property
    def is_member(self) -> bool:
        return self.xbrltype == 'domainItemType'

    @property
    def is_axis(self) -> bool:
        return self.localname.endswith('Axis')

    def calculation_in(self, role: str) -> Optional[CalculationEntry]:
        """Get calculation entry for a specific role, or None."""
        return self.calculations.get(role)

    def is_root_in(self, role: str) -> bool:
        """True if this tag is a calculation root in the given role."""
        entry = self.calculations.get(role)
        return entry.root if entry else False

    def __repr__(self):
        crdr_str = f", crdr={self.crdr}" if self.crdr else ""
        return f"TagDefinition({self.tag_id}{crdr_str})"


@dataclass
class MetaLinksReport:
    """Report entry from MetaLinks.json (mirrors FilingSummary Report)."""
    report_key: str
    role: str
    long_name: str
    short_name: str
    group_type: str
    sub_group_type: str
    menu_cat: str
    order: int
    first_anchor: Optional[str]
    unique_anchor: Optional[str]


@dataclass
class AuthRef:
    """FASB authoritative reference from std_ref."""
    ref_id: str
    role: str
    name: str
    topic: str
    sub_topic: str
    section: str
    paragraph: str
    publisher: str
    uri: str


class MetaLinks:
    """
    Parser and container for MetaLinks.json data.

    Provides access to tag definitions, calculation trees, report metadata,
    and FASB authoritative references for a single XBRL filing.

    Usage:
        metalinks = MetaLinks.parse(json_text)
        tag = metalinks.get_tag('us-gaap_Assets')
        tag.crdr           # 'debit'
        tag.documentation  # 'Amount of asset recognized for present right to economic benefit.'
        tag.label          # 'Assets'

        # Calculation tree
        children = metalinks.get_calculation_children('us-gaap_Assets', role_uri)
        tree = metalinks.get_calculation_tree('us-gaap_Assets', role_uri)

        # Search
        results = metalinks.search('revenue')
    """

    def __init__(self,
                 version: str,
                 instance_key: str,
                 tags: Dict[str, TagDefinition],
                 reports: Dict[str, MetaLinksReport],
                 auth_refs: Dict[str, AuthRef],
                 stats: dict):
        self.version = version
        self.instance_key = instance_key
        self._tags = tags
        self._reports = reports
        self._auth_refs = auth_refs
        self.stats = stats
        # Build reverse index: parent_tag -> [(child_tag_id, CalculationEntry)]
        self._calc_children: Dict[str, Dict[str, List[tuple]]] = {}  # role -> parent -> [(child_id, entry)]
        self._build_calc_children_index()
        # Build label index for search: lowercase label -> tag_id
        self._label_index: Dict[str, str] = {}
        for tag_id, tag in self._tags.items():
            if tag.terse_label:
                self._label_index[tag.terse_label.lower()] = tag_id
            if tag.label and tag.label.lower() != tag.terse_label.lower():
                self._label_index[tag.label.lower()] = tag_id
            if tag.total_label and tag.total_label.lower() not in self._label_index:
                self._label_index[tag.total_label.lower()] = tag_id

    def _build_calc_children_index(self):
        """Build reverse index from parent tags to their calculation children."""
        for tag_id, tag in self._tags.items():
            for role, entry in tag.calculations.items():
                if entry.parent_tag:
                    if role not in self._calc_children:
                        self._calc_children[role] = {}
                    role_children = self._calc_children[role]
                    if entry.parent_tag not in role_children:
                        role_children[entry.parent_tag] = []
                    role_children[entry.parent_tag].append((tag_id, entry))

    @classmethod
    def parse(cls, json_text: str) -> 'MetaLinks':
        """Parse MetaLinks.json content into structured objects."""
        data = json.loads(json_text)
        version = data.get('version', '')
        # Get the single instance entry
        instance_dict = data.get('instance', {})
        if not instance_dict:
            return cls(version=version, instance_key='', tags={}, reports={}, auth_refs={}, stats={})
        instance_key = next(iter(instance_dict))
        inst = instance_dict[instance_key]

        # Parse stats
        stats = {
            'key_standard': inst.get('keyStandard', 0),
            'key_custom': inst.get('keyCustom', 0),
            'axis_standard': inst.get('axisStandard', 0),
            'axis_custom': inst.get('axisCustom', 0),
            'member_standard': inst.get('memberStandard', 0),
            'member_custom': inst.get('memberCustom', 0),
            'context_count': inst.get('contextCount', 0),
            'entity_count': inst.get('entityCount', 0),
            'segment_count': inst.get('segmentCount', 0),
            'element_count': inst.get('elementCount', 0),
            'unit_count': inst.get('unitCount', 0),
        }

        # Parse tags
        tags = {}
        for tag_id, tag_data in inst.get('tag', {}).items():
            lang_data = tag_data.get('lang', {}).get('en-us', {}).get('role', {})
            # Parse calculation entries
            calculations = {}
            for role, calc_data in tag_data.get('calculation', {}).items():
                calculations[role] = CalculationEntry(
                    role=role,
                    parent_tag=calc_data.get('parentTag'),
                    weight=calc_data.get('weight'),
                    order=calc_data.get('order'),
                    root=bool(calc_data.get('root', False)),
                )
            tags[tag_id] = TagDefinition(
                tag_id=tag_id,
                xbrltype=tag_data.get('xbrltype', ''),
                nsuri=tag_data.get('nsuri', ''),
                localname=tag_data.get('localname', ''),
                crdr=tag_data.get('crdr'),
                label=lang_data.get('label', ''),
                terse_label=lang_data.get('terseLabel', lang_data.get('label', '')),
                total_label=lang_data.get('totalLabel'),
                documentation=lang_data.get('documentation', ''),
                presentation=tag_data.get('presentation', []),
                calculations=calculations,
                auth_ref_ids=tag_data.get('auth_ref', []),
            )

        # Parse reports
        reports = {}
        for rkey, rdata in inst.get('report', {}).items():
            first_anchor_name = None
            fa = rdata.get('firstAnchor')
            if fa:
                first_anchor_name = fa.get('name')
            unique_anchor_name = None
            ua = rdata.get('uniqueAnchor')
            if ua:
                unique_anchor_name = ua.get('name')
            reports[rkey] = MetaLinksReport(
                report_key=rkey,
                role=rdata.get('role', ''),
                long_name=rdata.get('longName', ''),
                short_name=rdata.get('shortName', ''),
                group_type=rdata.get('groupType', ''),
                sub_group_type=rdata.get('subGroupType', ''),
                menu_cat=rdata.get('menuCat', ''),
                order=int(rdata.get('order', 0)),
                first_anchor=first_anchor_name,
                unique_anchor=unique_anchor_name,
            )

        # Parse auth_refs
        auth_refs = {}
        for ref_id, ref_data in data.get('std_ref', {}).items():
            auth_refs[ref_id] = AuthRef(
                ref_id=ref_id,
                role=ref_data.get('role', ''),
                name=ref_data.get('Name', ''),
                topic=ref_data.get('Topic', ''),
                sub_topic=ref_data.get('SubTopic', ''),
                section=ref_data.get('Section', ''),
                paragraph=ref_data.get('Paragraph', ''),
                publisher=ref_data.get('Publisher', ''),
                uri=ref_data.get('URI', ''),
            )

        return cls(
            version=version,
            instance_key=instance_key,
            tags=tags,
            reports=reports,
            auth_refs=auth_refs,
            stats=stats,
        )

    # --- Tag access ---

    @property
    def tag_count(self) -> int:
        return len(self._tags)

    @property
    def report_count(self) -> int:
        return len(self._reports)

    def get_tag(self, tag_id: str) -> Optional[TagDefinition]:
        """Look up a tag by its qualified ID (e.g., 'us-gaap_Assets')."""
        return self._tags.get(tag_id)

    def get_tag_by_label(self, label: str) -> Optional[TagDefinition]:
        """Look up a tag by its label (case-insensitive)."""
        tag_id = self._label_index.get(label.lower())
        if tag_id:
            return self._tags.get(tag_id)
        return None

    @property
    def tags(self) -> Dict[str, TagDefinition]:
        return self._tags

    # --- Report access ---

    def get_report(self, report_key: str) -> Optional[MetaLinksReport]:
        """Look up a report by key (e.g., 'R2')."""
        return self._reports.get(report_key)

    def get_reports_by_category(self, category: str) -> List[MetaLinksReport]:
        """Get reports filtered by menu category."""
        return sorted(
            [r for r in self._reports.values() if r.menu_cat == category],
            key=lambda r: r.order
        )

    @property
    def reports(self) -> Dict[str, MetaLinksReport]:
        return self._reports

    # --- Auth refs ---

    def get_auth_ref(self, ref_id: str) -> Optional[AuthRef]:
        return self._auth_refs.get(ref_id)

    def get_auth_refs_for_tag(self, tag: TagDefinition) -> List[AuthRef]:
        """Get all authoritative references for a tag."""
        return [self._auth_refs[rid] for rid in tag.auth_ref_ids if rid in self._auth_refs]

    # --- Calculation tree ---

    def get_tags_for_role(self, role: str) -> List[TagDefinition]:
        """Get all tags that appear in a specific presentation role."""
        return [tag for tag in self._tags.values() if role in tag.presentation]

    def get_calculation_children(self, tag_id: str, role: str) -> List[TagDefinition]:
        """Get immediate calculation children of a tag in a given role, ordered."""
        role_children = self._calc_children.get(role, {})
        children = role_children.get(tag_id, [])
        children_sorted = sorted(children, key=lambda x: x[1].order or 0)
        return [self._tags[child_id] for child_id, _ in children_sorted if child_id in self._tags]

    def get_calculation_roots(self, role: str) -> List[TagDefinition]:
        """Get all calculation root tags for a given role."""
        roots = []
        for tag in self._tags.values():
            entry = tag.calculations.get(role)
            if entry and entry.root:
                roots.append(tag)
        return roots

    def get_calculation_tree(self, tag_id: str, role: str, max_depth: int = 10) -> dict:
        """
        Recursively build the full calculation tree for a concept in a role.

        Returns a nested dict:
            {
                'tag': TagDefinition,
                'weight': float,
                'order': float,
                'children': [...]
            }
        """
        tag = self._tags.get(tag_id)
        if not tag or max_depth <= 0:
            return {}
        entry = tag.calculations.get(role)
        children = self.get_calculation_children(tag_id, role)
        return {
            'tag': tag,
            'weight': entry.weight if entry else None,
            'order': entry.order if entry else None,
            'children': [
                self.get_calculation_tree(child.tag_id, role, max_depth - 1)
                for child in children
            ]
        }

    # --- Search ---

    def search(self, query: str, category: Optional[str] = None) -> List[TagDefinition]:
        """
        Search tags by label, localname, or documentation substring.

        Results are ranked: exact label > starts with > word match > substring.
        Optionally filter to tags appearing only in reports of a given category.
        """
        query_lower = query.lower()
        # Filter by category if requested
        if category:
            cat_reports = self.get_reports_by_category(category)
            cat_roles = {r.role for r in cat_reports}
            candidates = [t for t in self._tags.values() if any(r in cat_roles for r in t.presentation)]
        else:
            candidates = list(self._tags.values())

        exact = []
        starts = []
        word = []
        substring = []
        for tag in candidates:
            labels = [tag.terse_label.lower(), tag.label.lower(), tag.localname.lower()]
            if tag.total_label:
                labels.append(tag.total_label.lower())
            if any(l == query_lower for l in labels):
                exact.append(tag)
            elif any(l.startswith(query_lower) for l in labels):
                starts.append(tag)
            elif any(query_lower in l.split() for l in labels):
                word.append(tag)
            elif any(query_lower in l for l in labels) or query_lower in tag.documentation.lower():
                substring.append(tag)

        return exact + starts + word + substring

    def __len__(self):
        return self.tag_count

    def __repr__(self):
        return f"MetaLinks(tags={self.tag_count}, reports={self.report_count}, version={self.version})"
