"""
Regression test for Issue #683: StatementNotFound error when stitching cash flow for VALE

GitHub Issue: https://github.com/dgunning/edgartools/issues/683

Bug (FIXED): stitching cash flow across VALE's 20-F filings raised
`StatementNotFound` and aborted the whole operation.

Fix: Catch `StatementNotFound` in the stitching loop and skip filings that
don't have the requested statement type, rather than crashing.

CORRECTION TO THE PREMISE RECORDED HERE (2026-08-09). This file used to state
that VALE "doesn't include a cash flow statement presentation role in every
filing's XBRL", and the test below was written to accept an empty result on
that basis. That was wrong twice over. All three filings it loads declare the
role — "00000005 - Statement - Consolidated Statement of Cash Flows", typed
CashFlowStatement — and the empty result came from a second bug underneath:
the essential-concept gate rejected VALE's IFRS concepts, so the statement was
in the filing and unreachable through the API.

Fixed as edgartools-gi1n; the mechanism, the offline reproduction and VALE's
figures are in test_issue_gi1n_ifrs_cashflow_resolution.py. The stitching
regression this file is named for is a genuinely separate fix and is still
what the test below covers — now against a stitch that produces data, which
is the state in which "the loop skipped a filing" would actually show up.
"""

import pytest

from edgar.xbrl.exceptions import StatementNotFound


class TestStitchingSkipsMissingStatements:
    """Unit test: stitch_statements handles StatementNotFound gracefully."""

    def test_get_statement_by_type_exception_is_caught(self):
        """Verify that StatementNotFound from get_statement_by_type doesn't
        propagate out of the stitching loop — it should be caught and the
        filing skipped."""
        # StatementNotFound should be importable and is a proper exception
        exc = StatementNotFound(
            statement_type="CashFlowStatement",
            confidence=0.0,
            found_statements=[],
            entity_name="VALE S.A.",
            reason="No statements available in XBRL data",
        )
        assert isinstance(exc, Exception)
        assert "CashFlowStatement" in str(exc)


def _vale_20f_filings(n=3):
    from edgar import Company
    return Company('VALE').get_filings(form='20-F').head(n)


@pytest.mark.network
def test_vale_stitched_cashflow_no_crash():
    """#683 itself: the stitch completes instead of raising.

    The precondition is asserted first, because the old version of this test
    tolerated every outcome — `if cf is not None: assert df is not None` — and
    would have passed just as happily against a build where stitching returned
    nothing for any reason at all. Each filing must declare the cash flow role,
    or "the stitch skipped the filings that lack it" would be a different
    statement about a different set of filings.
    """
    from edgar.xbrl.stitching import XBRLS

    filings = _vale_20f_filings()
    for filing in filings:
        roles = [s for s in filing.xbrl().get_all_statements()
                 if s.get('type') == 'CashFlowStatement']
        assert [str(s['definition']) for s in roles] == \
            ['00000005 - Statement - Consolidated Statement of Cash Flows'], \
            f"{filing.accession_no} no longer declares exactly one cash flow role"

    xbrls = XBRLS.from_filings(filings)
    try:
        cf = xbrls.statements.cashflow_statement()
    except Exception as e:
        pytest.fail(f"Should not raise, got: {e}")

    assert cf is not None, "stitching produced no cash flow statement at all"
    df = cf.to_dataframe()

    # One column per filing, and the operating total present in each: a stitch
    # that silently dropped a filing loses a column, which is the failure this
    # test could not previously see.
    periods = [c for c in df.columns if str(c).startswith('20')]
    assert periods == ['2025-12-31', '2024-12-31', '2023-12-31'], \
        f"stitched periods are {periods}; one of the three filings was skipped"

    operating = df[df['concept'] == 'vale_CashFlowFromUsedInOperatingActivities']
    assert len(operating) == 1, "the operating total did not survive stitching"
    assert [operating.iloc[0][p] for p in periods] == \
        [8_801_000_000, 9_366_000_000, 13_165_000_000], \
        "net cash generated by operating activities, as reported in each 20-F"
