"""`get_operating_cash_flow()` returned None for Apple — GH #1083, bead edgartools-nrp0.

The method searched the cash flow statement for five label patterns written
against the STANDARDIZED vocabulary::

    ^Net Cash from Operating        ^Net Cash Provided by Operating
    Net Cash.*Operating Activities$ Operating.*Cash.*Flow
    Net Cash.*Operations$

Apple labels the line "Cash generated by operating activities", which matches
none of them, so the method returned None for every Apple filing — and
``get_free_cash_flow()`` returned None with it, silently, because it depends on
this value.

**The five issuers that worked, worked by coincidence of house style.** Measured
on the latest 10-K of each at the time of the fix: MSFT "Net cash from
operations", KO "Net Cash Provided by Operating Activities", NVDA "Net cash
provided by operating activities" — each happening to fall inside one of the
five patterns. Apple was not an outlier; it was the filer whose wording fell
outside the list.

The fix mirrors what ``get_revenue`` and ``get_capital_expenditures`` already
did: search by XBRL concept through the standardization store first, and keep
the label patterns as a fallback for statements whose concept is absent or
unmapped. The concept is the same for every filer regardless of wording.

Do NOT "fix" a future report of this shape by appending another regex — that
repairs one filer and leaves the next one broken, which is the whole point of
this file.
"""
import pandas as pd
import pytest

from edgar.financials import Financials

APPLE_10Q = "0000320193-26-000013"  # Apple 10-Q, period 2026-03-28


class _FakeRendered:
    """The minimum surface ``_get_standardized_concept_by_xbrl`` reads.

    ``periods`` is empty on purpose: ``_order_period_columns`` then leaves the
    dataframe's own column order alone, so these tests exercise concept lookup
    without also re-testing the period ordering fixed in GH #885.
    """

    periods = []

    def __init__(self, df):
        self._df = df

    def to_dataframe(self, presentation: bool = True):
        # The real method applies the presentation sign; the helper under test
        # asks for presentation=False because it wants filed magnitudes
        # (edgartools-5ztr). These rows are filed values either way.
        return self._df


class _FakeStatement:
    def __init__(self, df):
        self._df = df

    def render(self, standard=True):
        return _FakeRendered(self._df)


def _financials_over(df):
    """A Financials whose cash flow statement is `df`, with no network behind it."""

    class _Fin(Financials):
        def cash_flow_statement(self, include_dimensions=None, view=None):
            return _FakeStatement(df)

    # xb only has to be non-None: every code path under test checks it and then
    # goes through cash_flow_statement() above.
    return _Fin(xb=object())


def _row(concept, label, value):
    return {
        "concept": concept,
        "label": label,
        "abstract": False,
        "level": 2,
        "dimension": False,
        "is_breakdown": False,
        "2026-03-28": value,
    }


@pytest.mark.fast
def test_apples_wording_is_found_by_concept_not_by_label():
    """The regression itself: a label matching none of the five patterns.

    This is the assertion that fails on the pre-fix implementation.
    """
    df = pd.DataFrame([
        _row("us-gaap_NetCashProvidedByUsedInOperatingActivities",
             "Cash generated by operating activities",
             82_627_000_000),
    ])

    assert _financials_over(df).get_operating_cash_flow() == 82_627_000_000


@pytest.mark.fast
def test_label_fallback_still_answers_when_the_concept_is_unmapped():
    """A custom extension tag has no concept mapping — labels must still work.

    The fallback is not vestigial: it is what serves filers using extension tags
    and IFRS filers outside the mapping set. Deleting it would trade one class of
    silent None for another.
    """
    df = pd.DataFrame([
        _row("acme_CashFromOperationsCustomTag",
             "Net Cash from Operating Activities",
             1_234_000),
    ])

    assert _financials_over(df).get_operating_cash_flow() == 1_234_000


@pytest.mark.fast
def test_absent_line_still_returns_none():
    """No concept, no matching label: None is the correct answer, not a stray value."""
    df = pd.DataFrame([
        _row("us-gaap_NetIncomeLoss", "Net income", 23_000_000),
    ])

    assert _financials_over(df).get_operating_cash_flow() is None


@pytest.mark.network
def test_apple_10q_ground_truth():
    """Hand-verified against the filing: $82,627,000,000 for the quarter.

    Source: Apple 10-Q for the period ended 2026-03-28, cash flow statement,
    "Cash generated by operating activities", concept
    us-gaap_NetCashProvidedByUsedInOperatingActivities.
    """
    from edgar import get_by_accession_number

    financials = get_by_accession_number(APPLE_10Q).obj().financials

    assert financials.get_operating_cash_flow() == 82_627_000_000
    assert financials.get_operating_cash_flow(period_offset=1) == 53_887_000_000

    # The silent cascade in the same report: free cash flow was None purely
    # because operating cash flow was.
    assert financials.get_capital_expenditures() == 4_344_000_000
    assert financials.get_free_cash_flow() == 78_283_000_000


@pytest.mark.network
@pytest.mark.parametrize("ticker", ["MSFT", "KO", "NVDA", "JNJ", "XOM"])
def test_the_filers_that_already_worked_still_do(ticker):
    """No regression on the five whose labels happened to match.

    Asserted against the statement's own figure rather than a literal, because
    "the latest 10-K" moves each year and a hardcoded number here would rot into
    a false failure. The comparison is still exact.
    """
    from edgar import Company

    financials = Company(ticker).get_financials()
    df = financials.cash_flow_statement().render(standard=True).to_dataframe()

    rows = df[df["concept"].astype(str).str.endswith("NetCashProvidedByUsedInOperatingActivities")]
    assert not rows.empty, f"{ticker} has no operating-cash-flow concept to compare against"

    non_period = {"concept", "label", "level", "abstract", "dimension", "is_breakdown", "unit", "point_in_time"}
    period_columns = [c for c in df.columns if c not in non_period]
    expected = rows.iloc[0][period_columns[0]]

    assert financials.get_operating_cash_flow() == pytest.approx(float(expected))
