"""
Regression test for edgartools-t3zh (GH #1083): `render(standard=True)` produced
no standardization output at all on the rendered DataFrame, so the flag was
inert on that path.

THE BEAD'S PREMISE IS STALE AND THE FIX IS NOT WHAT IT ASKED FOR. It reports
that `render(standard=True)` "is documented to replace filer labels with
standardized ones" and replaces almost none of them — 1 of 26 mapped concepts on
Apple's FY2023 cash flow statement, which still reproduces exactly. But not
replacing them is deliberate: `standardize_statement()` says so in its own
docstring ("Add standard concept metadata to statement items without replacing
labels... preserves the original company labels (fidelity to the filing)"), and
`select_display_label` keeps a company's preferred or terse label on purpose so
that "Other intangible assets, net" does not become "Intangible Assets".
Forcing replacement would revert a decision, not fix a bug.

The consumer-level symptom the bead was filed for — `get_operating_cash_flow()`
returning None for Apple because its regexes expected standardized labels — was
fixed separately by concept-first lookup (edgartools-nrp0, #1089).

What was genuinely broken is the other half of that design. Standardization is
supposed to preserve the label AND report the standard concept alongside it.
`Statement.to_dataframe()` carries a `standard_concept` column;
`RenderedStatement.to_dataframe()` dropped it, even though the renderer had
already written it into each row's metadata. So the documented way to ask for
standardization returned a frame with no standardized anything in it, and a
caller could not tell `standard=True` from `standard=False`.
"""

from pathlib import Path

import pandas as pd
import pytest

from edgar.xbrl import XBRL

FIXTURE = Path("tests/fixtures/xbrl/aapl/10k_2023")

# AAPL FY2023 cash flow statement: filer label -> standard concept.
EXPECTED = {
    "us-gaap_NetCashProvidedByUsedInOperatingActivities": "NetCashFromOperatingActivities",
    "us-gaap_NetCashProvidedByUsedInFinancingActivities": "NetCashFromFinancingActivities",
    "us-gaap_RepaymentsOfLongTermDebt": "DebtRepayments",
    "us-gaap_ProceedsFromIssuanceOfLongTermDebt": "DebtProceeds",
}


@pytest.fixture(scope="module")
def cash_flow():
    return XBRL.from_directory(FIXTURE).statements["CashFlowStatement"]


def test_the_flag_produces_standardization(cash_flow):
    """`standard=True` returned a frame with no standardized anything."""
    df = cash_flow.render(standard=True).to_dataframe()

    assert "standard_concept" in df.columns
    assert df["standard_concept"].notna().sum() >= 20


def test_standard_false_carries_no_standard_column(cash_flow):
    """The control: the two settings have to be distinguishable."""
    df = cash_flow.render(standard=False).to_dataframe()

    assert "standard_concept" not in df.columns


def test_specific_concept_to_standard_pairs(cash_flow):
    """Ground truth, per the bead's definition of done."""
    df = cash_flow.render(standard=True).to_dataframe()
    resolved = {
        row["concept"]: row["standard_concept"]
        for _, row in df.iterrows()
        if pd.notna(row.get("standard_concept"))
    }

    for concept, standard in EXPECTED.items():
        assert resolved.get(concept) == standard, concept


def test_filer_labels_are_preserved(cash_flow):
    """
    The deliberate half of the design, pinned so it is not "fixed" later by
    overwriting labels: standardization reports the concept and leaves the
    filing's own wording alone.
    """
    df = cash_flow.render(standard=True).to_dataframe()
    labels = dict(zip(df["concept"], df["label"], strict=True))

    # Apple's own wording, not the standardized vocabulary.
    assert labels["us-gaap_NetCashProvidedByUsedInOperatingActivities"] == (
        "Cash generated by operating activities"
    )
    assert labels["us-gaap_RepaymentsOfLongTermDebt"] == "Repayments of term debt"


def test_both_dataframe_paths_agree_on_the_standard_concept(cash_flow):
    """
    The two accessors disagreed: one carried the column, the other dropped it.
    Where both report a concept, they must report the same one.
    """
    rendered = cash_flow.render(standard=True).to_dataframe()
    singular = cash_flow.to_dataframe()
    if "standard_concept" not in singular.columns:
        pytest.fail("Statement.to_dataframe() lost its standard_concept column")

    # pd.notna, not truthiness: a NaN is truthy and would slip through, and
    # then compare unequal to itself.
    a = {
        row["concept"]: row["standard_concept"]
        for _, row in rendered.iterrows()
        if pd.notna(row.get("standard_concept"))
    }
    b = {
        row["concept"]: row["standard_concept"]
        for _, row in singular.iterrows()
        if pd.notna(row.get("standard_concept"))
    }

    shared = set(a) & set(b)
    assert shared, "the two paths share no standardized concepts at all"
    for concept in shared:
        assert a[concept] == b[concept], concept
