"""Tests for filing agent fingerprinting."""

from edgar.documents.agents import (
    detect_filing_agent,
    WORKIVA, DONNELLEY, TOPPAN_MERRILL, NOVAWORKS,
    COMPSCI, CERTENT, BROADRIDGE, EDGARSUITE, SEC_PUBLISHER,
)


# --- Unit tests using synthetic HTML snippets ---

def test_detect_workiva():
    html = '<?xml version="1.0"?><!--XBRL Document Created with the Workiva Platform--><!--Copyright 2026 Workiva--><html><body>content</body></html>'
    assert detect_filing_agent(html) == WORKIVA


def test_detect_donnelley_dfin():
    html = '<!--DFIN New ActiveDisclosure (SM) Inline XBRL Document - http://www.dfinsolutions.com/--><html></html>'
    assert detect_filing_agent(html) == DONNELLEY


def test_detect_donnelley_by_name():
    html = '<!--Copyright (c) 2026 Donnelley Financial Solutions, Inc.--><html></html>'
    assert detect_filing_agent(html) == DONNELLEY


def test_detect_donnelley_by_url():
    html = '<!-- http://www.dfinsolutions.com/something --><html></html>'
    assert detect_filing_agent(html) == DONNELLEY


def test_detect_toppan_merrill():
    html = '<!-- Toppan Merrill - document generated --><html></html>'
    assert detect_filing_agent(html) == TOPPAN_MERRILL


def test_detect_toppan_merrill_by_merrill():
    html = '<!-- Merrill Corporation generated document --><html></html>'
    assert detect_filing_agent(html) == TOPPAN_MERRILL


def test_detect_novaworks_thunderdome():
    html = '<!-- Generated by ThunderDome Portal - 3/12/2026 8:44:09 PM --><html></html>'
    assert detect_filing_agent(html) == NOVAWORKS


def test_detect_novaworks_xdx():
    html = '<!-- Field: Set; Name: xdx; ID: xdx_02A_US%2DGAAP --><html></html>'
    assert detect_filing_agent(html) == NOVAWORKS


def test_detect_compsci():
    html = '<!-- Generated by CompSci Transform (tm) - http://www.compsciresources.com --><html></html>'
    assert detect_filing_agent(html) == COMPSCI


def test_detect_certent():
    html = '<!-- Inline XBRL document created by Certent Disclosure Management 1.0.0.0 --><html></html>'
    assert detect_filing_agent(html) == CERTENT


def test_detect_broadridge():
    html = '<!-- Licensed to: Broadridge\nDocument created using Broadridge PROfile 25.10.1.5333 --><html></html>'
    assert detect_filing_agent(html) == BROADRIDGE


def test_detect_edgarsuite():
    html = '<!-- Produced by EDGARsuite software, Advanced Computer Innovations, Inc. --><html></html>'
    assert detect_filing_agent(html) == EDGARSUITE


def test_detect_sec_publisher():
    html = '<HTML><HEAD><TITLE>Generated by SEC Publisher for SEC Filing</TITLE></HEAD></HTML>'
    assert detect_filing_agent(html) == SEC_PUBLISHER


def test_detect_unknown_returns_none():
    html = '<?xml version="1.0"?><html xmlns="http://www.w3.org/1999/xhtml"><body>plain filing</body></html>'
    assert detect_filing_agent(html) is None


def test_detect_empty_string():
    assert detect_filing_agent('') is None


def test_only_scans_first_3000_chars():
    """Signature appearing after 3000 chars should not be detected."""
    html = 'x' * 3001 + '<!--XBRL Document Created with the Workiva Platform-->'
    assert detect_filing_agent(html) is None


def test_signature_at_boundary():
    """Signature starting within first 3000 chars should be detected."""
    padding = 'x' * 2980
    html = padding + '<!--Workiva--><html></html>'
    assert detect_filing_agent(html) == WORKIVA
