ACRONYMS = {
    "CCC": "CIK Confirmation Code",
    "CIK": "Central Index Key",
    "EDGAR": "Electronic Data Gathering, Analysis, and Retrieval",
    "SEC": "Securities and Exchange Commission",
}

INVESTMENT_CATEGORIES = {
    "ABS": "Asset-backed securities",
    "ACMO": "Agency collateralized mortgage obligations",
    "ACMBS": "Agency debentures and agency strips",
    "AMBS": "Agency mortgage-backed securities",
    "UST": " U.S. Treasuries (including strips)",
    "N/A": "Not applicable"
}

ISO_STATES_AND_OUTLYING_AREAS = {
    "US-AL": "ALABAMA",
    "US-AK": "ALASKA",
    "US-AZ": "ARIZONA",
    "US-AR": "ARKANSAS",
    "US-CA": "CALIFORNIA",
    "US-CO": "COLORADO",
    "US-CT": "CONNECTICUT",
    "US-DE": "DELAWARE",
    "US-DC": "DISTRICT OF COLUMBIA",

}

ISO_COUNTRY_CODES = {
    "AF": " AFGHANISTAN",
    "AX": "ALAND ISLANDS",
    "AL": "ALBANIA",
    "DZ": "ALGERIA",
    "AS": "AMERICAN SAMOA",
    "AD": "ANDORRA",
    "AO": "ANGOLA",
    "AI": "ANGUILLA",
    "AQ": "ANTARCTICA",
    "AG": "ANTIGUA AND BARBUDA",
    "AR": "ARGENTINA",
    "AM": "ARMENIA",
    "AW": "ARUBA",
    "AU": "AUSTRALIA",
    "AT": "AUSTRIA",
    "AZ": "AZERBAIJAN",
    "BS": "BAHAMAS",
    "BH": "BAHRAIN",
    "BD": "BANGLADESH",
    "BB": "BARBADOS",
    "BY": "BELARUS",
    "BE": "BELGIUM",
    "BZ": "BELIZE",
    "BJ": "BENIN",
    "BM": "BERMUDA",
    "BT": "BHUTAN",
    "BO": "BOLIVIA (PLURINATIONAL STATE OF)",
    "BQ": "BONAIRE, SINT EUSTATIUS AND SABA",
    "BA": "BOSNIA AND HERZEGOVINA",
    "BW": "BOTSWANA",
    "BV": "BOUVET ISLAND",
    "BR": "BRAZIL",
    "IO": "BRITISH INDIAN OCEAN TERRITORY",
    "BN": "BRUNEI DARUSSALAM",
    "BG": "BULGARIA",
    "BF": "BURKINA FASO",
    "BI": "BURUNDI",
    "CV": "CABO VERDE",
    "KH": "CAMBODIA",
    "CM": "CAMEROON",
    "CA": "CANADA",
    "KY": "CAYMAN ISLANDS",
    "CF": "CENTRAL AFRICAN REPUBLIC",
    "TD": "CHAD",
    "CL": "CHILE",
    "CN": "CHINA",
    "CX": "CHRISTMAS ISLAND",
    "CC": "COCOS (KEELING) ISLANDS",
    "CO": "COLOMBIA",
    "KM": "COMOROS",
    "CG": "CONGO",
    "CD": "COOK ISLANDS",
    "CR": "COSTA RICA",
    "CI": "COTE D'IVOIRE",
    "HR": "CROATIA",
    "CU": "CUBA",
    "CW": "CURACAO",
    "CY": "CYPRUS",
    "CZ": "CZECHIA",
    "DK": "DENMARK",
    "DJ": "DJIBOUTI",
    "DM": "DOMINICA",
    "DO": "DOMINICAN REPUBLIC",
    "EC": "ECUADOR",
    "EG": "EGYPT",
    "SV": "EL SALVADOR",
    "GQ": "EQUATORIAL GUINEA",
    "ER": "ERITREA",
    "EE": "ESTONIA",
    "ET": "ETHIOPIA",
    "FK": "FALKLAND ISLANDS (MALVINAS)",
    "FO": "FAROE ISLANDS",
    "FJ": "FIJI",
    "FI": "FINLAND",
    "FR": "FRANCE",
    "GF": "FRENCH GUIANA",
    "PF": "FRENCH POLYNESIA",
    "TF": "FRENCH SOUTHERN TERRITORIES",
    "GA": "GABON",
    "GM": "GAMBIA",
}
